rabbitmq:
    queue:
        name: "javaguides"
        json:
            name: "javaguides_json"
    exchange:
        name: "javaguides_exchange"
    routing:
        key: "javaguides_routing_key"
        json:
            key: "javaguides_routing_json_key"